### ISSUE TITLE
Product update permissions (32. Ownership)

### ISSUE THREAD

**Issue by tullo** [ardanlabs/service-training#10]
The [readme](https://github.com/ardanlabs/service-training/blob/master/32-ownership/README.md) says:
> When updating products ensure that the client either has RoleAdmin or is the owner of the specified product.

But in the code it says: "You need to be admin AND own the product" in order to update the product.
```go
	if !user.HasRole(auth.RoleAdmin) && p.UserID != user.Subject {
		return ErrForbidden
	}
```
https://github.com/ardanlabs/service-training/blob/master/32-ownership/internal/product/product.go#L113

I guess the `&&` should be replaced with `||` so the code does what the readme says it should.

**Comment by ardan-bkennedy** [comment]
I am being @jcbwlkr in to this to make sure we get this right.

**Comment by jcbwlkr** [comment]
Hi @tullo. Thanks for the issue report and thanks for your email. I haven't been able to work on many OSS projects recently so please forgive the delay.

The code is correct. It is doing an early return so the logic has to be inverted from the way it is worded in the README. For example consider the difference between these two snippets


```go
if user.HasRole(auth.RoleAdmin) || p.UserID == user.Subject {
	// Continue with update procedure
} else {
	return ErrForbidden
}
```

and this form

```go
if !user.HasRole(auth.RoleAdmin) && p.UserID != user.Subject {
	return ErrForbidden
}

// Continue with update procedure
```

The first form would let the logic read is it is worded in the README but it would create an extra level of indentation. It is the idiom in Go to return early for errors and let the happy path run towards the bottom with less indentation.

I suppose you could write the code using an `||` but wrap the whole thing in a negation `!(...)` like this:

```go
if !(user.HasRole(auth.RoleAdmin) || p.UserID == user.Subject) {
	return ErrForbidden
}
```

But IMO this would be harder to understand.

**Comment by tullo** [comment]
Thanks @jcbwlkr for your reply! I actually prefer the last option. For me it is much easier to read and grasp that way.

When I created this issue I was tricked by the `!user.HasRole(auth.RoleAdmin)` part of the expression, but I can see now that the code is correct.
