### ISSUE TITLE
[Question] Unhandeled internal server error.

### ISSUE THREAD

**Issue by sreejeet** [ardanlabs/service-training#13]
In the file [main.go in 03-json](https://github.com/ardanlabs/service-training/blob/master/03-json/main.go) (Commit 338812d for future ref.)

If we get an error at line 99, wouldn't the client still receive an OK status as it was already declared at line 98, resulting in a server side error going unnoticed by the client?

From https://golang.org/pkg/net/http/
>     // If WriteHeader is not called explicitly, the first call to Write
>     // will trigger an implicit WriteHeader(http.StatusOK).
>     // Thus explicit calls to WriteHeader are mainly used to
>     // send error codes.

Shouldn't we instead use the error response code returned by w.Write() inside the if statement to explicitly set an error status code?

**Comment by ardan-bkennedy** [comment]
This code base is going away soon for the code that is in the
github.com/ardanlabs/service

I am not maintaining this going forward.

I believe the order of how things are called are handling this.

**Comment by sreejeet** [comment]
Oh, I understand.
Thanks.
