### ISSUE TITLE
Shouldn't the List method return a pointer to the slice?

### ISSUE THREAD

**Issue by tullo** [ardanlabs/service-training#9]
Hi, I'm just curious. The `Create` and `Get` methods for the product return a pointer but `List` returns a slice value. Shouldn't we return a pointer to the slice as well here?

`func List(db *sqlx.DB) ([]Product, error)`

https://github.com/ardanlabs/service-training/blob/master/09-routing/internal/product/product.go#L9
https://github.com/ardanlabs/service-training/blob/master/36-self-shutdown/internal/product/product.go#L29

**Comment by ardan-bkennedy** [comment]
No. You also pass a slice value. The slice value already contains a pointer to the backing array.
